import { ROLES, ADMIN_ROLES, isTutorLike as _isTutorLike, getPermissions, hasPermission } from "./roles";

export { ROLES, ADMIN_ROLES, getPermissions, hasPermission };
export const isTutorLike = (user?: { role?: string } | null): boolean => _isTutorLike(user?.role);

export const USER_STATUS = {
  ACTIVE: "ACTIVE",
  BLOCKED: "BLOCKED",
  DELETED: "DELETED",
} as const;

export const TUTOR_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  SUSPENDED: "SUSPENDED",
} as const;

export const COURSE_STATUS = {
  DRAFT: "DRAFT",
  PENDING: "PENDING",
  PUBLISHED: "PUBLISHED",
  REJECTED: "REJECTED",
  ARCHIVED: "ARCHIVED",
} as const;

export const ENROLLMENT_STATUS = {
  NOT_REQUESTED: "NOT_REQUESTED",
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
} as const;

export const LESSON_STATUS = {
  SCHEDULED: "SCHEDULED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export const BOOKING_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
} as const;

export const REPORT_TYPE = {
  USER: "USER",
  TUTOR: "TUTOR",
  COURSE: "COURSE",
  REVIEW: "REVIEW",
  LESSON: "LESSON",
} as const;

export const REPORT_STATUS = {
  OPEN: "OPEN",
  IN_REVIEW: "IN_REVIEW",
  RESOLVED: "RESOLVED",
  REJECTED: "REJECTED",
} as const;

export const NOTIFICATION_TYPES = {
  NEW_REQUEST: "NEW_REQUEST",
  REQUEST_ACCEPTED: "REQUEST_ACCEPTED",
  REQUEST_REJECTED: "REQUEST_REJECTED",
  LESSON_REMINDER: "LESSON_REMINDER",
  LESSON_CANCELLED: "LESSON_CANCELLED",
  NEW_MESSAGE: "NEW_MESSAGE",
  NEW_REVIEW: "NEW_REVIEW",
  TUTOR_APPROVED: "TUTOR_APPROVED",
  TUTOR_REJECTED: "TUTOR_REJECTED",
  COURSE_APPROVED: "COURSE_APPROVED",
  COURSE_REJECTED: "COURSE_REJECTED",
  SUPPORT_MESSAGE: "SUPPORT_MESSAGE",
  SUPPORT_TICKET_CREATED: "SUPPORT_TICKET_CREATED",
  SUPPORT_TICKET_ASSIGNED: "SUPPORT_TICKET_ASSIGNED",
  SUPPORT_TICKET_RESOLVED: "SUPPORT_TICKET_RESOLVED",
  SUPPORT_TICKET_CLOSED: "SUPPORT_TICKET_CLOSED",
} as const;