export const endpoints = {
  auth: {
    login: "/api/v1/auth/login",
    register: "/api/v1/auth/register",
    refresh: "/api/v1/auth/refresh",
    logout: "/api/v1/auth/logout",
    me: "/api/v1/auth/me",
    forgotPassword: "/api/v1/auth/forgot-password",
    resetPassword: "/api/v1/auth/reset-password",
    verifyEmail: "/api/v1/auth/verify-email",
    resendVerification: "/api/v1/auth/resend-verification",
    verifyResetCode: "/api/v1/auth/verify-reset-code",
    changeEmail: "/api/v1/auth/change-email",
  },
  tutors: {
    applications: "/api/v1/tutors/applications",
    myApplication: "/api/v1/tutors/applications/me",
    byId: (id: string | number) => `/api/v1/tutors/${id}`,
    availability: "/api/v1/availability",
    availabilityById: (id: string | number) => `/api/v1/availability/${id}`,
    availabilityByTeacher: (id: string | number) => `/api/v1/tutors/${id}/availability`,
  },
  users: {
    me: "/api/v1/users/me",
    byId: (id: string | number) => `/api/v1/users/${id}`,
    update: "/api/v1/users/me",
    avatar: "/api/v1/users/me/avatar",
    tutors: "/api/v1/users/tutors",
  },
  courses: {
    list: "/api/v1/courses",
    popular: "/api/v1/courses/popular",
    byId: (id: string | number) => `/api/v1/courses/${id}`,
    create: "/api/v1/courses",
    update: (id: string | number) => `/api/v1/courses/${id}`,
    delete: (id: string | number) => `/api/v1/courses/${id}`,
    byTeacher: (id: string | number) => `/api/v1/courses/teacher/${id}`,
    canReview: (courseId: string | number) => `/api/v1/courses/${courseId}/can-review`,
  },
  search: {
    courses: "/api/v1/search/courses",
    coursesV2: "/api/v1/search/courses/v2",
    suggestions: "/api/v1/search/suggestions",
    tutors: "/api/v1/search/tutors",
  },
  reviews: {
    list: (courseId: string | number) => `/api/v1/courses/${courseId}/reviews`,
    create: (courseId: string | number) => `/api/v1/courses/${courseId}/reviews`,
    createForBooking: (courseId: string | number, bookingId: string | number) =>
      `/api/v1/courses/${courseId}/reviews/booking/${bookingId}`,
  },
  bookings: {
    create: "/api/v1/bookings",
    byId: (id: string | number) => `/api/v1/bookings/${id}`,
    confirm: (id: string | number) => `/api/v1/bookings/${id}/confirm`,
    reject: (id: string | number) => `/api/v1/bookings/${id}/reject`,
    cancel: (id: string | number) => `/api/v1/bookings/${id}/cancel`,
    complete: (id: string | number) => `/api/v1/bookings/${id}/complete`,
    my: "/api/v1/bookings/me",
    teacher: "/api/v1/bookings/teacher",
  },
  enrollments: {
    enroll: (courseId: string | number) => `/api/v1/courses/${courseId}/enroll`,
    myEnrollments: "/api/v1/students/me/enrollments",
    tutorRequests: "/api/v1/tutors/me/requests",
    accept: (id: string | number) => `/api/v1/enrollments/${id}/accept`,
    acceptAndSchedule: (id: string | number) => `/api/v1/enrollments/${id}/accept-and-schedule`,
    reject: (id: string | number) => `/api/v1/enrollments/${id}/reject`,
    cancel: (id: string | number) => `/api/v1/enrollments/${id}`,
    forCourse: (courseId: string | number) => `/api/v1/courses/${courseId}/enrollment`,
  },
  lessons: {
    list: "/api/v1/lessons",
    byId: (id: string | number) => `/api/v1/lessons/${id}`,
    create: "/api/v1/lessons",
    cancel: (id: string | number) => `/api/v1/lessons/${id}/cancel`,
    complete: (id: string | number) => `/api/v1/lessons/${id}/complete`,
    start: (id: string | number) => `/api/v1/lessons/${id}/start`,
  },
  calendar: {
    range: (from: string, to: string) =>
      `/api/v1/calendar?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`,
  },
  messages: {
    conversations: "/api/v1/messages/conversations",
    conversation: (id: string | number) => `/api/v1/messages/conversations/${id}`,
    send: "/api/v1/messages",
  },
  meetings: {
    token: (bookingId: string | number) => `/api/v1/bookings/${bookingId}/meeting/token`,
    end: (bookingId: string | number) => `/api/v1/bookings/${bookingId}/meeting/end`,
  },
  notifications: {
    list: "/api/v1/notifications",
    unreadCount: "/api/v1/notifications/unread-count",
    markRead: (id: string | number) => `/api/v1/notifications/${id}/read`,
    markAllRead: "/api/v1/notifications/read-all",
  },
  support: {
    tickets: "/api/v1/support/tickets",
    ticket: (id: string | number) => `/api/v1/support/tickets/${id}`,
    messages: (id: string | number) => `/api/v1/support/tickets/${id}/messages`,
    send: (id: string | number) => `/api/v1/support/tickets/${id}/messages`,
    markRead: (id: string | number) => `/api/v1/support/tickets/${id}/read`,
    close: (id: string | number) => `/api/v1/support/tickets/${id}/close`,
    reopen: (id: string | number) => `/api/v1/support/tickets/${id}/reopen`,
  },
  adminSupport: {
    tickets: "/api/v1/admin/support/tickets",
    ticket: (id: string | number) => `/api/v1/admin/support/tickets/${id}`,
    assign: (id: string | number) => `/api/v1/admin/support/tickets/${id}/assign`,
    take: (id: string | number) => `/api/v1/admin/support/tickets/${id}/take`,
    status: (id: string | number) => `/api/v1/admin/support/tickets/${id}/status`,
    priority: (id: string | number) => `/api/v1/admin/support/tickets/${id}/priority`,
    agents: "/api/v1/admin/support/agents",
  },
  admin: {
    users: "/api/v1/admin/users",
    block: (id: string | number) => `/api/v1/admin/users/${id}/block`,
    unblock: (id: string | number) => `/api/v1/admin/users/${id}/unblock`,
    role: (id: string | number) => `/api/v1/admin/users/${id}/role`,
    verify: (id: string | number) => `/api/v1/admin/users/${id}/verify`,
    stats: "/api/v1/admin/stats",
    tutors: "/api/v1/admin/tutors",
    approveTutor: (id: string | number) => `/api/v1/admin/tutors/${id}/approve`,
    rejectTutor: (id: string | number) => `/api/v1/admin/tutors/${id}/reject`,
    courses: "/api/v1/admin/courses",
    approveCourse: (id: string | number) => `/api/v1/admin/courses/${id}/approve`,
    rejectCourse: (id: string | number) => `/api/v1/admin/courses/${id}/reject`,
    reviews: "/api/v1/admin/reviews",
    hideReview: (id: string | number) => `/api/v1/admin/reviews/${id}/hide`,
    restoreReview: (id: string | number) => `/api/v1/admin/reviews/${id}/restore`,
    reports: "/api/v1/admin/reports",
    updateReport: (id: string | number) => `/api/v1/admin/reports/${id}`,
  },
} as const;

export const pageParams = (page = 0, size = 20): string => `page=${page}&size=${size}`;